FROM golang:1.25-alpine

WORKDIR /app/cmd/api

# Install git (required for go mod download) and Air for live reloading
RUN apk add --no-cache git 
RUN go install github.com/air-verse/air@latest

ENV CGO_ENABLED=0

EXPOSE 8080

CMD ["sh", "-c", "go mod download && air -c .air.toml"]