FROM fabrizio2210/docker_light-default_container:latest

# Install Python 3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip && apt-get clean

# Install required Python libraries
RUN pip3 install pymongo argparse