# Stage 1: Build the Angular application
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package.json and package-lock.json
COPY src/js/coverletter-frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY src/js/coverletter-frontend/ ./

# Build the application for production
# The output will be in /app/dist/coverletter-frontend/browser
RUN npm run build -- --configuration production

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Copy the Nginx configuration file
COPY docker/x86_64/nginx.conf /etc/nginx/conf.d/default.conf

# Copy built assets from the 'builder' stage to the Nginx public directory
COPY --from=builder /app/dist/coverletter-frontend/browser /usr/share/nginx/html

EXPOSE 80