// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: src/go/internal/proto/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryPart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty" bson:"text"` // @gotags: bson:"text"
}

func (x *HistoryPart) Reset() {
	*x = HistoryPart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryPart) ProtoMessage() {}

func (x *HistoryPart) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryPart.ProtoReflect.Descriptor instead.
func (*HistoryPart) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type HistoryEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role  string         `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty" bson:"role"`   // @gotags: bson:"role"
	Parts []*HistoryPart `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty" bson:"parts"` // @gotags: bson:"parts"
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryEntry) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *HistoryEntry) GetParts() []*HistoryPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CoverLetter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id"`                                               // @gotags: bson:"id"
	RecipientId    string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty" bson:"recipient_id"`          // @gotags: bson:"recipient_id"
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty" bson:"conversation_id"` // @gotags: bson:"conversation_id"
	CoverLetter    string                 `protobuf:"bytes,4,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty" bson:"cover_letter"`          // @gotags: bson:"cover_letter"
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at"`                // @gotags: bson:"created_at"
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"`                // @gotags: bson:"updated_at"
	Prompt         string                 `protobuf:"bytes,7,opt,name=prompt,proto3" json:"prompt,omitempty" bson:"prompt"`                                       // @gotags: bson:"prompt"
	History        []*HistoryEntry        `protobuf:"bytes,8,rep,name=history,proto3" json:"history,omitempty" bson:"history"`                                     // @gotags: bson:"history"
}

func (x *CoverLetter) Reset() {
	*x = CoverLetter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoverLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverLetter) ProtoMessage() {}

func (x *CoverLetter) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverLetter.ProtoReflect.Descriptor instead.
func (*CoverLetter) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *CoverLetter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CoverLetter) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *CoverLetter) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CoverLetter) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *CoverLetter) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CoverLetter) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CoverLetter) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CoverLetter) GetHistory() []*HistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

var File_src_go_internal_proto_common_common_proto protoreflect.FileDescriptor

var file_src_go_internal_proto_common_common_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x50,
	0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x4d, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x70,
	0x61, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x72, 0x74, 0x52,
	0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x22, 0xca, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x76, 0x65, 0x72,
	0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x74, 0x74,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x4c,
	0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x7a, 0x69, 0x6f, 0x32, 0x32, 0x31, 0x30, 0x2f, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_go_internal_proto_common_common_proto_rawDescOnce sync.Once
	file_src_go_internal_proto_common_common_proto_rawDescData = file_src_go_internal_proto_common_common_proto_rawDesc
)

func file_src_go_internal_proto_common_common_proto_rawDescGZIP() []byte {
	file_src_go_internal_proto_common_common_proto_rawDescOnce.Do(func() {
		file_src_go_internal_proto_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_go_internal_proto_common_common_proto_rawDescData)
	})
	return file_src_go_internal_proto_common_common_proto_rawDescData
}

var file_src_go_internal_proto_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_go_internal_proto_common_common_proto_goTypes = []interface{}{
	(*HistoryPart)(nil),           // 0: common.HistoryPart
	(*HistoryEntry)(nil),          // 1: common.HistoryEntry
	(*CoverLetter)(nil),           // 2: common.CoverLetter
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_src_go_internal_proto_common_common_proto_depIdxs = []int32{
	0, // 0: common.HistoryEntry.parts:type_name -> common.HistoryPart
	3, // 1: common.CoverLetter.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: common.CoverLetter.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: common.CoverLetter.history:type_name -> common.HistoryEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_go_internal_proto_common_common_proto_init() }
func file_src_go_internal_proto_common_common_proto_init() {
	if File_src_go_internal_proto_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_go_internal_proto_common_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryPart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoverLetter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_go_internal_proto_common_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_go_internal_proto_common_common_proto_goTypes,
		DependencyIndexes: file_src_go_internal_proto_common_common_proto_depIdxs,
		MessageInfos:      file_src_go_internal_proto_common_common_proto_msgTypes,
	}.Build()
	File_src_go_internal_proto_common_common_proto = out.File
	file_src_go_internal_proto_common_common_proto_rawDesc = nil
	file_src_go_internal_proto_common_common_proto_goTypes = nil
	file_src_go_internal_proto_common_common_proto_depIdxs = nil
}
