// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: src/go/internal/proto/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoringStatus int32

const (
	ScoringStatus_SCORING_STATUS_UNSPECIFIED ScoringStatus = 0
	ScoringStatus_SCORING_STATUS_UNSCORED    ScoringStatus = 1
	ScoringStatus_SCORING_STATUS_QUEUED      ScoringStatus = 2
	ScoringStatus_SCORING_STATUS_SCORED      ScoringStatus = 3
	ScoringStatus_SCORING_STATUS_FAILED      ScoringStatus = 4
	ScoringStatus_SCORING_STATUS_SKIPPED     ScoringStatus = 5
)

// Enum value maps for ScoringStatus.
var (
	ScoringStatus_name = map[int32]string{
		0: "SCORING_STATUS_UNSPECIFIED",
		1: "SCORING_STATUS_UNSCORED",
		2: "SCORING_STATUS_QUEUED",
		3: "SCORING_STATUS_SCORED",
		4: "SCORING_STATUS_FAILED",
		5: "SCORING_STATUS_SKIPPED",
	}
	ScoringStatus_value = map[string]int32{
		"SCORING_STATUS_UNSPECIFIED": 0,
		"SCORING_STATUS_UNSCORED":    1,
		"SCORING_STATUS_QUEUED":      2,
		"SCORING_STATUS_SCORED":      3,
		"SCORING_STATUS_FAILED":      4,
		"SCORING_STATUS_SKIPPED":     5,
	}
)

func (x ScoringStatus) Enum() *ScoringStatus {
	p := new(ScoringStatus)
	*p = x
	return p
}

func (x ScoringStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScoringStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_go_internal_proto_common_common_proto_enumTypes[0].Descriptor()
}

func (ScoringStatus) Type() protoreflect.EnumType {
	return &file_src_go_internal_proto_common_common_proto_enumTypes[0]
}

func (x ScoringStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScoringStatus.Descriptor instead.
func (ScoringStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{0}
}

type HistoryPart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty" bson:"text"` // @gotags: bson:"text"
}

func (x *HistoryPart) Reset() {
	*x = HistoryPart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryPart) ProtoMessage() {}

func (x *HistoryPart) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryPart.ProtoReflect.Descriptor instead.
func (*HistoryPart) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type HistoryEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role  string         `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty" bson:"role"`   // @gotags: bson:"role"
	Parts []*HistoryPart `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty" bson:"parts"` // @gotags: bson:"parts"
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryEntry) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *HistoryEntry) GetParts() []*HistoryPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CoverLetter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`                                               // @gotags: bson:"_id"
	RecipientId    string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty" bson:"recipient_id"`          // @gotags: bson:"recipient_id"
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty" bson:"conversation_id"` // @gotags: bson:"conversation_id"
	CoverLetter    string                 `protobuf:"bytes,4,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty" bson:"cover_letter"`          // @gotags: bson:"cover_letter"
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at"`                // @gotags: bson:"created_at"
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"`                // @gotags: bson:"updated_at"
	Prompt         string                 `protobuf:"bytes,7,opt,name=prompt,proto3" json:"prompt,omitempty" bson:"prompt"`                                       // @gotags: bson:"prompt"
	History        []*HistoryEntry        `protobuf:"bytes,8,rep,name=history,proto3" json:"history,omitempty" bson:"history"`                                     // @gotags: bson:"history"
	// Recipient info populated by aggregation lookup
	RecipientInfo *Recipient `protobuf:"bytes,9,opt,name=recipient_info,json=recipientInfo,proto3" json:"recipient_info,omitempty" bson:"recipientInfo,omitempty"` // @gotags: bson:"recipientInfo,omitempty"
}

func (x *CoverLetter) Reset() {
	*x = CoverLetter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoverLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverLetter) ProtoMessage() {}

func (x *CoverLetter) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverLetter.ProtoReflect.Descriptor instead.
func (*CoverLetter) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *CoverLetter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CoverLetter) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *CoverLetter) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CoverLetter) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *CoverLetter) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CoverLetter) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CoverLetter) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CoverLetter) GetHistory() []*HistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *CoverLetter) GetRecipientInfo() *Recipient {
	if x != nil {
		return x.RecipientInfo
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`       // @gotags: bson:"_id,omitempty"
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty" bson:"field"` // @gotags: bson:"field"
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *Field) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Field) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type CompanyDiscoverySource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source     string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty" bson:"source"`                           // @gotags: bson:"source"
	Role       string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty" bson:"role"`                               // @gotags: bson:"role"
	SourceUrl  string `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty" bson:"source_url,omitempty"`    // @gotags: bson:"source_url,omitempty"
	CareersUrl string `protobuf:"bytes,4,opt,name=careers_url,json=careersUrl,proto3" json:"careers_url,omitempty" bson:"careers_url,omitempty"` // @gotags: bson:"careers_url,omitempty"
	Domain     string `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty" bson:"domain,omitempty"`                           // @gotags: bson:"domain,omitempty"
}

func (x *CompanyDiscoverySource) Reset() {
	*x = CompanyDiscoverySource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyDiscoverySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyDiscoverySource) ProtoMessage() {}

func (x *CompanyDiscoverySource) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyDiscoverySource.ProtoReflect.Descriptor instead.
func (*CompanyDiscoverySource) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *CompanyDiscoverySource) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CompanyDiscoverySource) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CompanyDiscoverySource) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *CompanyDiscoverySource) GetCareersUrl() string {
	if x != nil {
		return x.CareersUrl
	}
	return ""
}

func (x *CompanyDiscoverySource) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type DiscoveredCompany struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" bson:"name"`                               // @gotags: bson:"name"
	Source      string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty" bson:"source"`                           // @gotags: bson:"source"
	Role        string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty" bson:"role"`                               // @gotags: bson:"role"
	SourceUrl   string `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty" bson:"source_url,omitempty"`    // @gotags: bson:"source_url,omitempty"
	CareersUrl  string `protobuf:"bytes,5,opt,name=careers_url,json=careersUrl,proto3" json:"careers_url,omitempty" bson:"careers_url,omitempty"` // @gotags: bson:"careers_url,omitempty"
	Domain      string `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty" bson:"domain,omitempty"`                           // @gotags: bson:"domain,omitempty"
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty" bson:"description,omitempty"`                 // @gotags: bson:"description,omitempty"
}

func (x *DiscoveredCompany) Reset() {
	*x = DiscoveredCompany{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveredCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredCompany) ProtoMessage() {}

func (x *DiscoveredCompany) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredCompany.ProtoReflect.Descriptor instead.
func (*DiscoveredCompany) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoveredCompany) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiscoveredCompany) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DiscoveredCompany) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DiscoveredCompany) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *DiscoveredCompany) GetCareersUrl() string {
	if x != nil {
		return x.CareersUrl
	}
	return ""
}

func (x *DiscoveredCompany) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DiscoveredCompany) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CompanySlugSearchAttempt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttemptedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=attempted_at,json=attemptedAt,proto3" json:"attempted_at,omitempty" bson:"attempted_at,omitempty"` // @gotags: bson:"attempted_at,omitempty"
	Attempts    int32                  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty" bson:"attempts,omitempty"`                         // @gotags: bson:"attempts,omitempty"
	Outcome     string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty" bson:"outcome,omitempty"`                            // @gotags: bson:"outcome,omitempty"
}

func (x *CompanySlugSearchAttempt) Reset() {
	*x = CompanySlugSearchAttempt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanySlugSearchAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanySlugSearchAttempt) ProtoMessage() {}

func (x *CompanySlugSearchAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanySlugSearchAttempt.ProtoReflect.Descriptor instead.
func (*CompanySlugSearchAttempt) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{6}
}

func (x *CompanySlugSearchAttempt) GetAttemptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttemptedAt
	}
	return nil
}

func (x *CompanySlugSearchAttempt) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *CompanySlugSearchAttempt) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type Workflow2TerminalFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FailureType string                 `protobuf:"bytes,1,opt,name=failure_type,json=failureType,proto3" json:"failure_type,omitempty" bson:"failure_type,omitempty"` // @gotags: bson:"failure_type,omitempty"
	FailedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty" bson:"failed_at,omitempty"`          // @gotags: bson:"failed_at,omitempty"
	LastUrl     string                 `protobuf:"bytes,3,opt,name=last_url,json=lastUrl,proto3" json:"last_url,omitempty" bson:"last_url,omitempty"`             // @gotags: bson:"last_url,omitempty"
	Message     string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty" bson:"message,omitempty"`                            // @gotags: bson:"message,omitempty"
}

func (x *Workflow2TerminalFailure) Reset() {
	*x = Workflow2TerminalFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workflow2TerminalFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow2TerminalFailure) ProtoMessage() {}

func (x *Workflow2TerminalFailure) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow2TerminalFailure.ProtoReflect.Descriptor instead.
func (*Workflow2TerminalFailure) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{7}
}

func (x *Workflow2TerminalFailure) GetFailureType() string {
	if x != nil {
		return x.FailureType
	}
	return ""
}

func (x *Workflow2TerminalFailure) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *Workflow2TerminalFailure) GetLastUrl() string {
	if x != nil {
		return x.LastUrl
	}
	return ""
}

func (x *Workflow2TerminalFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Company struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`                                                                                                                                                                 // @gotags: bson:"_id,omitempty"
	Name                     string                               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name"`                                                                                                                                                             // @gotags: bson:"name"
	FieldId                  string                               `protobuf:"bytes,3,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty" bson:"field_id"`                                                                                                                                        // @gotags: bson:"field_id"
	FieldInfo                *Field                               `protobuf:"bytes,4,opt,name=field_info,json=fieldInfo,proto3" json:"field_info,omitempty" bson:"fieldInfo,omitempty"`                                                                                                                                  // @gotags: bson:"fieldInfo,omitempty"
	Description              string                               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty" bson:"description,omitempty"`                                                                                                                                               // @gotags: bson:"description,omitempty"
	CanonicalName            string                               `protobuf:"bytes,6,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty" bson:"canonical_name,omitempty"`                                                                                                                      // @gotags: bson:"canonical_name,omitempty"
	DiscoverySources         []*CompanyDiscoverySource            `protobuf:"bytes,7,rep,name=discovery_sources,json=discoverySources,proto3" json:"discovery_sources,omitempty" bson:"discovery_sources,omitempty"`                                                                                                             // @gotags: bson:"discovery_sources,omitempty"
	AtsProvider              string                               `protobuf:"bytes,8,opt,name=ats_provider,json=atsProvider,proto3" json:"ats_provider,omitempty" bson:"ats_provider,omitempty"`                                                                                                                            // @gotags: bson:"ats_provider,omitempty"
	AtsSlug                  string                               `protobuf:"bytes,9,opt,name=ats_slug,json=atsSlug,proto3" json:"ats_slug,omitempty" bson:"ats_slug,omitempty"`                                                                                                                                        // @gotags: bson:"ats_slug,omitempty"
	AtsSlugSearchAttempts    map[string]*CompanySlugSearchAttempt `protobuf:"bytes,10,rep,name=ats_slug_search_attempts,json=atsSlugSearchAttempts,proto3" json:"ats_slug_search_attempts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"ats_slug_search_attempts,omitempty"` // @gotags: bson:"ats_slug_search_attempts,omitempty"
	Workflow2TerminalFailure *Workflow2TerminalFailure            `protobuf:"bytes,11,opt,name=workflow2_terminal_failure,json=workflow2TerminalFailure,proto3" json:"workflow2_terminal_failure,omitempty" bson:"workflow2_terminal_failure,omitempty"`                                                                                  // @gotags: bson:"workflow2_terminal_failure,omitempty"
}

func (x *Company) Reset() {
	*x = Company{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{8}
}

func (x *Company) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *Company) GetFieldInfo() *Field {
	if x != nil {
		return x.FieldInfo
	}
	return nil
}

func (x *Company) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Company) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

func (x *Company) GetDiscoverySources() []*CompanyDiscoverySource {
	if x != nil {
		return x.DiscoverySources
	}
	return nil
}

func (x *Company) GetAtsProvider() string {
	if x != nil {
		return x.AtsProvider
	}
	return ""
}

func (x *Company) GetAtsSlug() string {
	if x != nil {
		return x.AtsSlug
	}
	return ""
}

func (x *Company) GetAtsSlugSearchAttempts() map[string]*CompanySlugSearchAttempt {
	if x != nil {
		return x.AtsSlugSearchAttempts
	}
	return nil
}

func (x *Company) GetWorkflow2TerminalFailure() *Workflow2TerminalFailure {
	if x != nil {
		return x.Workflow2TerminalFailure
	}
	return nil
}

type Recipient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`                                      // @gotags: bson:"_id,omitempty"
	Email       string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty" bson:"email"`                                // @gotags: bson:"email"
	Name        string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" bson:"name"`                                  // @gotags: bson:"name"
	Description string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty" bson:"description"`                    // @gotags: bson:"description"
	CompanyId   string   `protobuf:"bytes,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty" bson:"company_id"`       // @gotags: bson:"company_id"
	CompanyInfo *Company `protobuf:"bytes,6,opt,name=company_info,json=companyInfo,proto3" json:"company_info,omitempty" bson:"companyInfo,omitempty"` // @gotags: bson:"companyInfo,omitempty"
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{9}
}

func (x *Recipient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recipient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Recipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipient) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recipient) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Recipient) GetCompanyInfo() *Company {
	if x != nil {
		return x.CompanyInfo
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`                                            // @gotags: bson:"_id,omitempty"
	Identity      string   `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty" bson:"identity"`                                // @gotags: bson:"identity"
	Name          string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" bson:"name"`                                        // @gotags: bson:"name"
	Description   string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty" bson:"description"`                          // @gotags: bson:"description"
	FieldId       string   `protobuf:"bytes,5,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty" bson:"field_id"`                   // @gotags: bson:"field_id"
	Roles         []string `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty" bson:"roles,omitempty"`                                      // @gotags: bson:"roles,omitempty"
	HtmlSignature string   `protobuf:"bytes,7,opt,name=html_signature,json=htmlSignature,proto3" json:"html_signature,omitempty" bson:"html_signature,omitempty"` // @gotags: bson:"html_signature,omitempty"
	FieldInfo     *Field   `protobuf:"bytes,8,opt,name=field_info,json=fieldInfo,proto3" json:"field_info,omitempty" bson:"fieldInfo,omitempty"`             // @gotags: bson:"fieldInfo,omitempty"
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{10}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Identity) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *Identity) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Identity) GetHtmlSignature() string {
	if x != nil {
		return x.HtmlSignature
	}
	return ""
}

func (x *Identity) GetFieldInfo() *Field {
	if x != nil {
		return x.FieldInfo
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`                                                                        // @gotags: bson:"_id,omitempty"
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty" bson:"company_id"`                                         // @gotags: bson:"company_id"
	CompanyInfo   *Company               `protobuf:"bytes,3,opt,name=company_info,json=companyInfo,proto3" json:"company_info,omitempty" bson:"companyInfo,omitempty"`                                   // @gotags: bson:"companyInfo,omitempty"
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty" bson:"title"`                                                                  // @gotags: bson:"title"
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty" bson:"description"`                                                      // @gotags: bson:"description"
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty" bson:"location"`                                                            // @gotags: bson:"location"
	Platform      string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty" bson:"platform"`                                                            // @gotags: bson:"platform"
	ExternalJobId string                 `protobuf:"bytes,8,opt,name=external_job_id,json=externalJobId,proto3" json:"external_job_id,omitempty" bson:"external_job_id"`                           // @gotags: bson:"external_job_id"
	SourceUrl     string                 `protobuf:"bytes,9,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty" bson:"source_url"`                                         // @gotags: bson:"source_url"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at"`                                        // @gotags: bson:"created_at"
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"`                                        // @gotags: bson:"updated_at"
	ScoringStatus ScoringStatus          `protobuf:"varint,12,opt,name=scoring_status,json=scoringStatus,proto3,enum=common.ScoringStatus" json:"scoring_status,omitempty" bson:"scoring_status"` // @gotags: bson:"scoring_status"
	WeightedScore float64                `protobuf:"fixed64,13,opt,name=weighted_score,json=weightedScore,proto3" json:"weighted_score,omitempty" bson:"weighted_score"`                          // @gotags: bson:"weighted_score"
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_go_internal_proto_common_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_src_go_internal_proto_common_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_src_go_internal_proto_common_common_proto_rawDescGZIP(), []int{11}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Job) GetCompanyInfo() *Company {
	if x != nil {
		return x.CompanyInfo
	}
	return nil
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Job) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Job) GetExternalJobId() string {
	if x != nil {
		return x.ExternalJobId
	}
	return ""
}

func (x *Job) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Job) GetScoringStatus() ScoringStatus {
	if x != nil {
		return x.ScoringStatus
	}
	return ScoringStatus_SCORING_STATUS_UNSPECIFIED
}

func (x *Job) GetWeightedScore() float64 {
	if x != nil {
		return x.WeightedScore
	}
	return 0
}

var File_src_go_internal_proto_common_common_proto protoreflect.FileDescriptor

var file_src_go_internal_proto_common_common_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x50,
	0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x4d, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x70,
	0x61, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x72, 0x74, 0x52,
	0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x22, 0x84, 0x03, 0x0a, 0x0b, 0x43, 0x6f, 0x76, 0x65, 0x72,
	0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x74, 0x74,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x4c,
	0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x38, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x0d,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2d, 0x0a,
	0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x9c, 0x01, 0x0a,
	0x16, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55,
	0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x73, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x73,
	0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xcd, 0x01, 0x0a, 0x11,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x73, 0x55, 0x72,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8f, 0x01, 0x0a, 0x18,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x53, 0x6c, 0x75, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x22, 0xab, 0x01,
	0x0a, 0x18, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x32, 0x54, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a,
	0x09, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x66, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x72,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xfb, 0x04, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69,
	0x63, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a,
	0x11, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x10, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x74,
	0x73, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x74, 0x73, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x74, 0x73, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x63, 0x0a, 0x18, 0x61, 0x74, 0x73, 0x5f,
	0x73, 0x6c, 0x75, 0x67, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x41, 0x74, 0x73, 0x53,
	0x6c, 0x75, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x15, 0x61, 0x74, 0x73, 0x53, 0x6c, 0x75, 0x67, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x12, 0x5e, 0x0a,
	0x1a, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x32, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x32, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x52, 0x18, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x32, 0x54, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x1a, 0x6a, 0x0a,
	0x1a, 0x41, 0x74, 0x73, 0x53, 0x6c, 0x75, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x74,
	0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x53, 0x6c, 0x75,
	0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xba, 0x01, 0x0a, 0x09, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x64, 0x12, 0x32, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xf2, 0x01, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x74, 0x6d, 0x6c, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x68, 0x74, 0x6d, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2c, 0x0a,
	0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xfa, 0x03, 0x0a, 0x03,
	0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x64, 0x12, 0x32, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x5f, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x3c, 0x0a, 0x0e, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x0d, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x65, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x2a, 0xb9, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x6f,
	0x72, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x43,
	0x4f, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x43,
	0x4f, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53,
	0x43, 0x4f, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x43, 0x4f, 0x52, 0x49,
	0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x43, 0x4f, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x43, 0x4f, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x19, 0x0a,
	0x15, 0x53, 0x43, 0x4f, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x43, 0x4f, 0x52,
	0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x4b, 0x49, 0x50, 0x50,
	0x45, 0x44, 0x10, 0x05, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x7a, 0x69, 0x6f, 0x32, 0x32, 0x31, 0x30, 0x2f,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_src_go_internal_proto_common_common_proto_rawDescOnce sync.Once
	file_src_go_internal_proto_common_common_proto_rawDescData = file_src_go_internal_proto_common_common_proto_rawDesc
)

func file_src_go_internal_proto_common_common_proto_rawDescGZIP() []byte {
	file_src_go_internal_proto_common_common_proto_rawDescOnce.Do(func() {
		file_src_go_internal_proto_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_go_internal_proto_common_common_proto_rawDescData)
	})
	return file_src_go_internal_proto_common_common_proto_rawDescData
}

var file_src_go_internal_proto_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_go_internal_proto_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_src_go_internal_proto_common_common_proto_goTypes = []interface{}{
	(ScoringStatus)(0),               // 0: common.ScoringStatus
	(*HistoryPart)(nil),              // 1: common.HistoryPart
	(*HistoryEntry)(nil),             // 2: common.HistoryEntry
	(*CoverLetter)(nil),              // 3: common.CoverLetter
	(*Field)(nil),                    // 4: common.Field
	(*CompanyDiscoverySource)(nil),   // 5: common.CompanyDiscoverySource
	(*DiscoveredCompany)(nil),        // 6: common.DiscoveredCompany
	(*CompanySlugSearchAttempt)(nil), // 7: common.CompanySlugSearchAttempt
	(*Workflow2TerminalFailure)(nil), // 8: common.Workflow2TerminalFailure
	(*Company)(nil),                  // 9: common.Company
	(*Recipient)(nil),                // 10: common.Recipient
	(*Identity)(nil),                 // 11: common.Identity
	(*Job)(nil),                      // 12: common.Job
	nil,                              // 13: common.Company.AtsSlugSearchAttemptsEntry
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_src_go_internal_proto_common_common_proto_depIdxs = []int32{
	1,  // 0: common.HistoryEntry.parts:type_name -> common.HistoryPart
	14, // 1: common.CoverLetter.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: common.CoverLetter.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: common.CoverLetter.history:type_name -> common.HistoryEntry
	10, // 4: common.CoverLetter.recipient_info:type_name -> common.Recipient
	14, // 5: common.CompanySlugSearchAttempt.attempted_at:type_name -> google.protobuf.Timestamp
	14, // 6: common.Workflow2TerminalFailure.failed_at:type_name -> google.protobuf.Timestamp
	4,  // 7: common.Company.field_info:type_name -> common.Field
	5,  // 8: common.Company.discovery_sources:type_name -> common.CompanyDiscoverySource
	13, // 9: common.Company.ats_slug_search_attempts:type_name -> common.Company.AtsSlugSearchAttemptsEntry
	8,  // 10: common.Company.workflow2_terminal_failure:type_name -> common.Workflow2TerminalFailure
	9,  // 11: common.Recipient.company_info:type_name -> common.Company
	4,  // 12: common.Identity.field_info:type_name -> common.Field
	9,  // 13: common.Job.company_info:type_name -> common.Company
	14, // 14: common.Job.created_at:type_name -> google.protobuf.Timestamp
	14, // 15: common.Job.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 16: common.Job.scoring_status:type_name -> common.ScoringStatus
	7,  // 17: common.Company.AtsSlugSearchAttemptsEntry.value:type_name -> common.CompanySlugSearchAttempt
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_src_go_internal_proto_common_common_proto_init() }
func file_src_go_internal_proto_common_common_proto_init() {
	if File_src_go_internal_proto_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_go_internal_proto_common_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryPart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoverLetter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyDiscoverySource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveredCompany); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanySlugSearchAttempt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workflow2TerminalFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Company); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recipient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_go_internal_proto_common_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_go_internal_proto_common_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_go_internal_proto_common_common_proto_goTypes,
		DependencyIndexes: file_src_go_internal_proto_common_common_proto_depIdxs,
		EnumInfos:         file_src_go_internal_proto_common_common_proto_enumTypes,
		MessageInfos:      file_src_go_internal_proto_common_common_proto_msgTypes,
	}.Build()
	File_src_go_internal_proto_common_common_proto = out.File
	file_src_go_internal_proto_common_common_proto_rawDesc = nil
	file_src_go_internal_proto_common_common_proto_goTypes = nil
	file_src_go_internal_proto_common_common_proto_depIdxs = nil
}
