"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class HistoryPart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TEXT_FIELD_NUMBER: builtins.int
    text: typing.Text
    """@gotags: bson:"text" """

    def __init__(self,
        *,
        text: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["text",b"text"]) -> None: ...
global___HistoryPart = HistoryPart

class HistoryEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ROLE_FIELD_NUMBER: builtins.int
    PARTS_FIELD_NUMBER: builtins.int
    role: typing.Text
    """@gotags: bson:"role" """

    @property
    def parts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryPart]:
        """@gotags: bson:"parts" """
        pass
    def __init__(self,
        *,
        role: typing.Text = ...,
        parts: typing.Optional[typing.Iterable[global___HistoryPart]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["parts",b"parts","role",b"role"]) -> None: ...
global___HistoryEntry = HistoryEntry

class CoverLetter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    RECIPIENT_ID_FIELD_NUMBER: builtins.int
    CONVERSATION_ID_FIELD_NUMBER: builtins.int
    COVER_LETTER_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    PROMPT_FIELD_NUMBER: builtins.int
    HISTORY_FIELD_NUMBER: builtins.int
    RECIPIENT_INFO_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id" """

    recipient_id: typing.Text
    """@gotags: bson:"recipient_id" """

    conversation_id: typing.Text
    """@gotags: bson:"conversation_id" """

    cover_letter: typing.Text
    """@gotags: bson:"cover_letter" """

    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"created_at" """
        pass
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"updated_at" """
        pass
    prompt: typing.Text
    """@gotags: bson:"prompt" """

    @property
    def history(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryEntry]:
        """@gotags: bson:"history" """
        pass
    @property
    def recipient_info(self) -> global___Recipient:
        """Recipient info populated by aggregation lookup
        @gotags: bson:"recipientInfo,omitempty"
        """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        recipient_id: typing.Text = ...,
        conversation_id: typing.Text = ...,
        cover_letter: typing.Text = ...,
        created_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        prompt: typing.Text = ...,
        history: typing.Optional[typing.Iterable[global___HistoryEntry]] = ...,
        recipient_info: typing.Optional[global___Recipient] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at",b"created_at","recipient_info",b"recipient_info","updated_at",b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["conversation_id",b"conversation_id","cover_letter",b"cover_letter","created_at",b"created_at","history",b"history","id",b"id","prompt",b"prompt","recipient_id",b"recipient_id","recipient_info",b"recipient_info","updated_at",b"updated_at"]) -> None: ...
global___CoverLetter = CoverLetter

class Field(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    FIELD_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    field: typing.Text
    """@gotags: bson:"field" """

    def __init__(self,
        *,
        id: typing.Text = ...,
        field: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["field",b"field","id",b"id"]) -> None: ...
global___Field = Field

class CompanyDiscoverySource(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOURCE_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    SOURCE_URL_FIELD_NUMBER: builtins.int
    CAREERS_URL_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    source: typing.Text
    """@gotags: bson:"source" """

    role: typing.Text
    """@gotags: bson:"role" """

    source_url: typing.Text
    """@gotags: bson:"source_url,omitempty" """

    careers_url: typing.Text
    """@gotags: bson:"careers_url,omitempty" """

    domain: typing.Text
    """@gotags: bson:"domain,omitempty" """

    def __init__(self,
        *,
        source: typing.Text = ...,
        role: typing.Text = ...,
        source_url: typing.Text = ...,
        careers_url: typing.Text = ...,
        domain: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["careers_url",b"careers_url","domain",b"domain","role",b"role","source",b"source","source_url",b"source_url"]) -> None: ...
global___CompanyDiscoverySource = CompanyDiscoverySource

class DiscoveredCompany(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    SOURCE_URL_FIELD_NUMBER: builtins.int
    CAREERS_URL_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    name: typing.Text
    """@gotags: bson:"name" """

    source: typing.Text
    """@gotags: bson:"source" """

    role: typing.Text
    """@gotags: bson:"role" """

    source_url: typing.Text
    """@gotags: bson:"source_url,omitempty" """

    careers_url: typing.Text
    """@gotags: bson:"careers_url,omitempty" """

    domain: typing.Text
    """@gotags: bson:"domain,omitempty" """

    description: typing.Text
    """@gotags: bson:"description,omitempty" """

    def __init__(self,
        *,
        name: typing.Text = ...,
        source: typing.Text = ...,
        role: typing.Text = ...,
        source_url: typing.Text = ...,
        careers_url: typing.Text = ...,
        domain: typing.Text = ...,
        description: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["careers_url",b"careers_url","description",b"description","domain",b"domain","name",b"name","role",b"role","source",b"source","source_url",b"source_url"]) -> None: ...
global___DiscoveredCompany = DiscoveredCompany

class CompanySlugSearchAttempt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ATTEMPTED_AT_FIELD_NUMBER: builtins.int
    ATTEMPTS_FIELD_NUMBER: builtins.int
    OUTCOME_FIELD_NUMBER: builtins.int
    @property
    def attempted_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"attempted_at,omitempty" """
        pass
    attempts: builtins.int
    """@gotags: bson:"attempts,omitempty" """

    outcome: typing.Text
    """@gotags: bson:"outcome,omitempty" """

    def __init__(self,
        *,
        attempted_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        attempts: builtins.int = ...,
        outcome: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["attempted_at",b"attempted_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attempted_at",b"attempted_at","attempts",b"attempts","outcome",b"outcome"]) -> None: ...
global___CompanySlugSearchAttempt = CompanySlugSearchAttempt

class Workflow2TerminalFailure(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FAILURE_TYPE_FIELD_NUMBER: builtins.int
    FAILED_AT_FIELD_NUMBER: builtins.int
    LAST_URL_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    failure_type: typing.Text
    """@gotags: bson:"failure_type,omitempty" """

    @property
    def failed_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"failed_at,omitempty" """
        pass
    last_url: typing.Text
    """@gotags: bson:"last_url,omitempty" """

    message: typing.Text
    """@gotags: bson:"message,omitempty" """

    def __init__(self,
        *,
        failure_type: typing.Text = ...,
        failed_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        last_url: typing.Text = ...,
        message: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["failed_at",b"failed_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["failed_at",b"failed_at","failure_type",b"failure_type","last_url",b"last_url","message",b"message"]) -> None: ...
global___Workflow2TerminalFailure = Workflow2TerminalFailure

class Company(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class AtsSlugSearchAttemptsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> global___CompanySlugSearchAttempt: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[global___CompanySlugSearchAttempt] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    FIELD_ID_FIELD_NUMBER: builtins.int
    FIELD_INFO_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CANONICAL_NAME_FIELD_NUMBER: builtins.int
    DISCOVERY_SOURCES_FIELD_NUMBER: builtins.int
    ATS_PROVIDER_FIELD_NUMBER: builtins.int
    ATS_SLUG_FIELD_NUMBER: builtins.int
    ATS_SLUG_SEARCH_ATTEMPTS_FIELD_NUMBER: builtins.int
    WORKFLOW2_TERMINAL_FAILURE_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    name: typing.Text
    """@gotags: bson:"name" """

    field_id: typing.Text
    """@gotags: bson:"field" """

    @property
    def field_info(self) -> global___Field:
        """@gotags: bson:"fieldInfo,omitempty" """
        pass
    description: typing.Text
    """@gotags: bson:"description,omitempty" """

    canonical_name: typing.Text
    """@gotags: bson:"canonical_name,omitempty" """

    @property
    def discovery_sources(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CompanyDiscoverySource]:
        """@gotags: bson:"discovery_sources,omitempty" """
        pass
    ats_provider: typing.Text
    """@gotags: bson:"ats_provider,omitempty" """

    ats_slug: typing.Text
    """@gotags: bson:"ats_slug,omitempty" """

    @property
    def ats_slug_search_attempts(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___CompanySlugSearchAttempt]:
        """@gotags: bson:"ats_slug_search_attempts,omitempty" """
        pass
    @property
    def workflow2_terminal_failure(self) -> global___Workflow2TerminalFailure:
        """@gotags: bson:"workflow2_terminal_failure,omitempty" """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        name: typing.Text = ...,
        field_id: typing.Text = ...,
        field_info: typing.Optional[global___Field] = ...,
        description: typing.Text = ...,
        canonical_name: typing.Text = ...,
        discovery_sources: typing.Optional[typing.Iterable[global___CompanyDiscoverySource]] = ...,
        ats_provider: typing.Text = ...,
        ats_slug: typing.Text = ...,
        ats_slug_search_attempts: typing.Optional[typing.Mapping[typing.Text, global___CompanySlugSearchAttempt]] = ...,
        workflow2_terminal_failure: typing.Optional[global___Workflow2TerminalFailure] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["field_info",b"field_info","workflow2_terminal_failure",b"workflow2_terminal_failure"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ats_provider",b"ats_provider","ats_slug",b"ats_slug","ats_slug_search_attempts",b"ats_slug_search_attempts","canonical_name",b"canonical_name","description",b"description","discovery_sources",b"discovery_sources","field_id",b"field_id","field_info",b"field_info","id",b"id","name",b"name","workflow2_terminal_failure",b"workflow2_terminal_failure"]) -> None: ...
global___Company = Company

class Recipient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    COMPANY_ID_FIELD_NUMBER: builtins.int
    COMPANY_INFO_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    email: typing.Text
    """@gotags: bson:"email" """

    name: typing.Text
    """@gotags: bson:"name" """

    description: typing.Text
    """@gotags: bson:"description" """

    company_id: typing.Text
    """@gotags: bson:"company" """

    @property
    def company_info(self) -> global___Company:
        """@gotags: bson:"companyInfo,omitempty" """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        email: typing.Text = ...,
        name: typing.Text = ...,
        description: typing.Text = ...,
        company_id: typing.Text = ...,
        company_info: typing.Optional[global___Company] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["company_info",b"company_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["company_id",b"company_id","company_info",b"company_info","description",b"description","email",b"email","id",b"id","name",b"name"]) -> None: ...
global___Recipient = Recipient

class Identity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    IDENTITY_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    FIELD_ID_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    HTML_SIGNATURE_FIELD_NUMBER: builtins.int
    FIELD_INFO_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    identity: typing.Text
    """@gotags: bson:"identity" """

    name: typing.Text
    """@gotags: bson:"name" """

    description: typing.Text
    """@gotags: bson:"description" """

    field_id: typing.Text
    """@gotags: bson:"field" """

    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """@gotags: bson:"roles,omitempty" """
        pass
    html_signature: typing.Text
    """@gotags: bson:"html_signature,omitempty" """

    @property
    def field_info(self) -> global___Field:
        """@gotags: bson:"fieldInfo,omitempty" """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        identity: typing.Text = ...,
        name: typing.Text = ...,
        description: typing.Text = ...,
        field_id: typing.Text = ...,
        roles: typing.Optional[typing.Iterable[typing.Text]] = ...,
        html_signature: typing.Text = ...,
        field_info: typing.Optional[global___Field] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["field_info",b"field_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description",b"description","field_id",b"field_id","field_info",b"field_info","html_signature",b"html_signature","id",b"id","identity",b"identity","name",b"name","roles",b"roles"]) -> None: ...
global___Identity = Identity
