# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n\x0bHistoryPart\x12\x0c\n\x04text\x18\x01 \x01(\t\"@\n\x0cHistoryEntry\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\"\n\x05parts\x18\x02 \x03(\x0b\x32\x13.common.HistoryPart\"\xf5\x01\n\x0b\x43overLetter\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0crecipient_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x03 \x01(\t\x12\x14\n\x0c\x63over_letter\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06prompt\x18\x07 \x01(\t\x12%\n\x07history\x18\x08 \x03(\x0b\x32\x14.common.HistoryEntryBCZAgithub.com/fabrizio2210/cover_letter/src/go/internal/proto/commonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZAgithub.com/fabrizio2210/cover_letter/src/go/internal/proto/common'
  _HISTORYPART._serialized_start=57
  _HISTORYPART._serialized_end=84
  _HISTORYENTRY._serialized_start=86
  _HISTORYENTRY._serialized_end=150
  _COVERLETTER._serialized_start=153
  _COVERLETTER._serialized_end=398
# @@protoc_insertion_point(module_scope)
