"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ScoringStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ScoringStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ScoringStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SCORING_STATUS_UNSPECIFIED: _ScoringStatus.ValueType  # 0
    SCORING_STATUS_UNSCORED: _ScoringStatus.ValueType  # 1
    SCORING_STATUS_QUEUED: _ScoringStatus.ValueType  # 2
    SCORING_STATUS_SCORED: _ScoringStatus.ValueType  # 3
    SCORING_STATUS_FAILED: _ScoringStatus.ValueType  # 4
    SCORING_STATUS_SKIPPED: _ScoringStatus.ValueType  # 5

class ScoringStatus(_ScoringStatus, metaclass=_ScoringStatusEnumTypeWrapper): ...

SCORING_STATUS_UNSPECIFIED: ScoringStatus.ValueType  # 0
SCORING_STATUS_UNSCORED: ScoringStatus.ValueType  # 1
SCORING_STATUS_QUEUED: ScoringStatus.ValueType  # 2
SCORING_STATUS_SCORED: ScoringStatus.ValueType  # 3
SCORING_STATUS_FAILED: ScoringStatus.ValueType  # 4
SCORING_STATUS_SKIPPED: ScoringStatus.ValueType  # 5
Global___ScoringStatus: _TypeAlias = ScoringStatus  # noqa: Y015

@_typing.final
class HistoryPart(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    """@gotags: bson:"text" """
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HistoryPart: _TypeAlias = HistoryPart  # noqa: Y015

@_typing.final
class HistoryEntry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ROLE_FIELD_NUMBER: _builtins.int
    PARTS_FIELD_NUMBER: _builtins.int
    role: _builtins.str
    """@gotags: bson:"role" """
    @_builtins.property
    def parts(self) -> _containers.RepeatedCompositeFieldContainer[Global___HistoryPart]:
        """@gotags: bson:"parts" """

    def __init__(
        self,
        *,
        role: _builtins.str = ...,
        parts: _abc.Iterable[Global___HistoryPart] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["parts", b"parts", "role", b"role"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HistoryEntry: _TypeAlias = HistoryEntry  # noqa: Y015

@_typing.final
class CoverLetter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    RECIPIENT_ID_FIELD_NUMBER: _builtins.int
    CONVERSATION_ID_FIELD_NUMBER: _builtins.int
    COVER_LETTER_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    PROMPT_FIELD_NUMBER: _builtins.int
    HISTORY_FIELD_NUMBER: _builtins.int
    RECIPIENT_INFO_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """@gotags: bson:"_id" """
    recipient_id: _builtins.str
    """@gotags: bson:"recipient_id" """
    conversation_id: _builtins.str
    """@gotags: bson:"conversation_id" """
    cover_letter: _builtins.str
    """@gotags: bson:"cover_letter" """
    prompt: _builtins.str
    """@gotags: bson:"prompt" """
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp:
        """@gotags: bson:"created_at" """

    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp:
        """@gotags: bson:"updated_at" """

    @_builtins.property
    def history(self) -> _containers.RepeatedCompositeFieldContainer[Global___HistoryEntry]:
        """@gotags: bson:"history" """

    @_builtins.property
    def recipient_info(self) -> Global___Recipient:
        """Recipient info populated by aggregation lookup
        @gotags: bson:"recipientInfo,omitempty"
        """

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        recipient_id: _builtins.str = ...,
        conversation_id: _builtins.str = ...,
        cover_letter: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
        prompt: _builtins.str = ...,
        history: _abc.Iterable[Global___HistoryEntry] | None = ...,
        recipient_info: Global___Recipient | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "recipient_info", b"recipient_info", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conversation_id", b"conversation_id", "cover_letter", b"cover_letter", "created_at", b"created_at", "history", b"history", "id", b"id", "prompt", b"prompt", "recipient_id", b"recipient_id", "recipient_info", b"recipient_info", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CoverLetter: _TypeAlias = CoverLetter  # noqa: Y015

@_typing.final
class Field(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    FIELD_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """@gotags: bson:"_id,omitempty" """
    field: _builtins.str
    """@gotags: bson:"field" """
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        field: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field", b"field", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Field: _TypeAlias = Field  # noqa: Y015

@_typing.final
class CompanyDiscoverySource(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    SOURCE_URL_FIELD_NUMBER: _builtins.int
    CAREERS_URL_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    """@gotags: bson:"source" """
    role: _builtins.str
    """@gotags: bson:"role" """
    source_url: _builtins.str
    """@gotags: bson:"source_url,omitempty" """
    careers_url: _builtins.str
    """@gotags: bson:"careers_url,omitempty" """
    domain: _builtins.str
    """@gotags: bson:"domain,omitempty" """
    def __init__(
        self,
        *,
        source: _builtins.str = ...,
        role: _builtins.str = ...,
        source_url: _builtins.str = ...,
        careers_url: _builtins.str = ...,
        domain: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["careers_url", b"careers_url", "domain", b"domain", "role", b"role", "source", b"source", "source_url", b"source_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompanyDiscoverySource: _TypeAlias = CompanyDiscoverySource  # noqa: Y015

@_typing.final
class DiscoveredCompany(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    SOURCE_URL_FIELD_NUMBER: _builtins.int
    CAREERS_URL_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """@gotags: bson:"name" """
    source: _builtins.str
    """@gotags: bson:"source" """
    role: _builtins.str
    """@gotags: bson:"role" """
    source_url: _builtins.str
    """@gotags: bson:"source_url,omitempty" """
    careers_url: _builtins.str
    """@gotags: bson:"careers_url,omitempty" """
    domain: _builtins.str
    """@gotags: bson:"domain,omitempty" """
    description: _builtins.str
    """@gotags: bson:"description,omitempty" """
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        source: _builtins.str = ...,
        role: _builtins.str = ...,
        source_url: _builtins.str = ...,
        careers_url: _builtins.str = ...,
        domain: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["careers_url", b"careers_url", "description", b"description", "domain", b"domain", "name", b"name", "role", b"role", "source", b"source", "source_url", b"source_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DiscoveredCompany: _TypeAlias = DiscoveredCompany  # noqa: Y015

@_typing.final
class CompanySlugSearchAttempt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ATTEMPTED_AT_FIELD_NUMBER: _builtins.int
    ATTEMPTS_FIELD_NUMBER: _builtins.int
    OUTCOME_FIELD_NUMBER: _builtins.int
    attempts: _builtins.int
    """@gotags: bson:"attempts,omitempty" """
    outcome: _builtins.str
    """@gotags: bson:"outcome,omitempty" """
    @_builtins.property
    def attempted_at(self) -> _timestamp_pb2.Timestamp:
        """@gotags: bson:"attempted_at,omitempty" """

    def __init__(
        self,
        *,
        attempted_at: _timestamp_pb2.Timestamp | None = ...,
        attempts: _builtins.int = ...,
        outcome: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attempted_at", b"attempted_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attempted_at", b"attempted_at", "attempts", b"attempts", "outcome", b"outcome"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompanySlugSearchAttempt: _TypeAlias = CompanySlugSearchAttempt  # noqa: Y015

@_typing.final
class EnrichmentAtsEnrichmentTerminalFailure(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FAILURE_TYPE_FIELD_NUMBER: _builtins.int
    FAILED_AT_FIELD_NUMBER: _builtins.int
    LAST_URL_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    failure_type: _builtins.str
    """@gotags: bson:"failure_type,omitempty" """
    last_url: _builtins.str
    """@gotags: bson:"last_url,omitempty" """
    message: _builtins.str
    """@gotags: bson:"message,omitempty" """
    @_builtins.property
    def failed_at(self) -> _timestamp_pb2.Timestamp:
        """@gotags: bson:"failed_at,omitempty" """

    def __init__(
        self,
        *,
        failure_type: _builtins.str = ...,
        failed_at: _timestamp_pb2.Timestamp | None = ...,
        last_url: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failed_at", b"failed_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failed_at", b"failed_at", "failure_type", b"failure_type", "last_url", b"last_url", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EnrichmentAtsEnrichmentTerminalFailure: _TypeAlias = EnrichmentAtsEnrichmentTerminalFailure  # noqa: Y015

@_typing.final
class Company(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AtsSlugSearchAttemptsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___CompanySlugSearchAttempt: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___CompanySlugSearchAttempt | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    FIELD_ID_FIELD_NUMBER: _builtins.int
    FIELD_INFO_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    CANONICAL_NAME_FIELD_NUMBER: _builtins.int
    DISCOVERY_SOURCES_FIELD_NUMBER: _builtins.int
    ATS_PROVIDER_FIELD_NUMBER: _builtins.int
    ATS_SLUG_FIELD_NUMBER: _builtins.int
    ATS_SLUG_SEARCH_ATTEMPTS_FIELD_NUMBER: _builtins.int
    ENRICHMENT_ATS_ENRICHMENT_TERMINAL_FAILURE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """@gotags: bson:"_id,omitempty" """
    name: _builtins.str
    """@gotags: bson:"name" """
    field_id: _builtins.str
    """@gotags: bson:"field_id" """
    description: _builtins.str
    """@gotags: bson:"description,omitempty" """
    canonical_name: _builtins.str
    """@gotags: bson:"canonical_name,omitempty" """
    ats_provider: _builtins.str
    """@gotags: bson:"ats_provider,omitempty" """
    ats_slug: _builtins.str
    """@gotags: bson:"ats_slug,omitempty" """
    @_builtins.property
    def field_info(self) -> Global___Field:
        """@gotags: bson:"fieldInfo,omitempty" """

    @_builtins.property
    def discovery_sources(self) -> _containers.RepeatedCompositeFieldContainer[Global___CompanyDiscoverySource]:
        """@gotags: bson:"discovery_sources,omitempty" """

    @_builtins.property
    def ats_slug_search_attempts(self) -> _containers.MessageMap[_builtins.str, Global___CompanySlugSearchAttempt]:
        """@gotags: bson:"ats_slug_search_attempts,omitempty" """

    @_builtins.property
    def enrichment_ats_enrichment_terminal_failure(self) -> Global___EnrichmentAtsEnrichmentTerminalFailure:
        """@gotags: bson:"enrichment_ats_enrichment_terminal_failure,omitempty" """

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        field_id: _builtins.str = ...,
        field_info: Global___Field | None = ...,
        description: _builtins.str = ...,
        canonical_name: _builtins.str = ...,
        discovery_sources: _abc.Iterable[Global___CompanyDiscoverySource] | None = ...,
        ats_provider: _builtins.str = ...,
        ats_slug: _builtins.str = ...,
        ats_slug_search_attempts: _abc.Mapping[_builtins.str, Global___CompanySlugSearchAttempt] | None = ...,
        enrichment_ats_enrichment_terminal_failure: Global___EnrichmentAtsEnrichmentTerminalFailure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["enrichment_ats_enrichment_terminal_failure", b"enrichment_ats_enrichment_terminal_failure", "field_info", b"field_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ats_provider", b"ats_provider", "ats_slug", b"ats_slug", "ats_slug_search_attempts", b"ats_slug_search_attempts", "canonical_name", b"canonical_name", "description", b"description", "discovery_sources", b"discovery_sources", "enrichment_ats_enrichment_terminal_failure", b"enrichment_ats_enrichment_terminal_failure", "field_id", b"field_id", "field_info", b"field_info", "id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Company: _TypeAlias = Company  # noqa: Y015

@_typing.final
class Recipient(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    COMPANY_ID_FIELD_NUMBER: _builtins.int
    COMPANY_INFO_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """@gotags: bson:"_id,omitempty" """
    email: _builtins.str
    """@gotags: bson:"email" """
    name: _builtins.str
    """@gotags: bson:"name" """
    description: _builtins.str
    """@gotags: bson:"description" """
    company_id: _builtins.str
    """@gotags: bson:"company_id" """
    @_builtins.property
    def company_info(self) -> Global___Company:
        """@gotags: bson:"companyInfo,omitempty" """

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        email: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        company_id: _builtins.str = ...,
        company_info: Global___Company | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["company_info", b"company_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["company_id", b"company_id", "company_info", b"company_info", "description", b"description", "email", b"email", "id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Recipient: _TypeAlias = Recipient  # noqa: Y015

@_typing.final
class Identity(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    IDENTITY_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    FIELD_ID_FIELD_NUMBER: _builtins.int
    ROLES_FIELD_NUMBER: _builtins.int
    HTML_SIGNATURE_FIELD_NUMBER: _builtins.int
    FIELD_INFO_FIELD_NUMBER: _builtins.int
    PREFERENCES_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """@gotags: bson:"_id,omitempty" """
    identity: _builtins.str
    """@gotags: bson:"identity" """
    name: _builtins.str
    """@gotags: bson:"name" """
    description: _builtins.str
    """@gotags: bson:"description" """
    field_id: _builtins.str
    """@gotags: bson:"field_id" """
    html_signature: _builtins.str
    """@gotags: bson:"html_signature,omitempty" """
    @_builtins.property
    def roles(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """@gotags: bson:"roles,omitempty" """

    @_builtins.property
    def field_info(self) -> Global___Field:
        """@gotags: bson:"fieldInfo,omitempty" """

    @_builtins.property
    def preferences(self) -> _containers.RepeatedCompositeFieldContainer[Global___IdentityPreference]:
        """@gotags: bson:"preferences,omitempty" """

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        identity: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        field_id: _builtins.str = ...,
        roles: _abc.Iterable[_builtins.str] | None = ...,
        html_signature: _builtins.str = ...,
        field_info: Global___Field | None = ...,
        preferences: _abc.Iterable[Global___IdentityPreference] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["field_info", b"field_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "field_id", b"field_id", "field_info", b"field_info", "html_signature", b"html_signature", "id", b"id", "identity", b"identity", "name", b"name", "preferences", b"preferences", "roles", b"roles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Identity: _TypeAlias = Identity  # noqa: Y015

@_typing.final
class IdentityPreference(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    GUIDANCE_FIELD_NUMBER: _builtins.int
    WEIGHT_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    """@gotags: bson:"key" """
    guidance: _builtins.str
    """@gotags: bson:"guidance,omitempty" """
    weight: _builtins.float
    """@gotags: bson:"weight" """
    enabled: _builtins.bool
    """@gotags: bson:"enabled" """
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        guidance: _builtins.str = ...,
        weight: _builtins.float = ...,
        enabled: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "guidance", b"guidance", "key", b"key", "weight", b"weight"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IdentityPreference: _TypeAlias = IdentityPreference  # noqa: Y015

@_typing.final
class PreferenceScore(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREFERENCE_KEY_FIELD_NUMBER: _builtins.int
    PREFERENCE_GUIDANCE_FIELD_NUMBER: _builtins.int
    PREFERENCE_WEIGHT_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    RATIONALE_FIELD_NUMBER: _builtins.int
    SCORED_AT_FIELD_NUMBER: _builtins.int
    preference_key: _builtins.str
    """@gotags: bson:"preference_key" """
    preference_guidance: _builtins.str
    """@gotags: bson:"preference_guidance,omitempty" """
    preference_weight: _builtins.float
    """@gotags: bson:"preference_weight,omitempty" """
    score: _builtins.int
    """@gotags: bson:"score" """
    rationale: _builtins.str
    """@gotags: bson:"rationale,omitempty" """
    @_builtins.property
    def scored_at(self) -> _timestamp_pb2.Timestamp:
        """@gotags: bson:"scored_at,omitempty" """

    def __init__(
        self,
        *,
        preference_key: _builtins.str = ...,
        preference_guidance: _builtins.str = ...,
        preference_weight: _builtins.float = ...,
        score: _builtins.int = ...,
        rationale: _builtins.str = ...,
        scored_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["scored_at", b"scored_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["preference_guidance", b"preference_guidance", "preference_key", b"preference_key", "preference_weight", b"preference_weight", "rationale", b"rationale", "score", b"score", "scored_at", b"scored_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PreferenceScore: _TypeAlias = PreferenceScore  # noqa: Y015

@_typing.final
class JobPreferenceScore(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    JOB_ID_FIELD_NUMBER: _builtins.int
    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    PREFERENCE_SCORES_FIELD_NUMBER: _builtins.int
    SCORING_STATUS_FIELD_NUMBER: _builtins.int
    WEIGHTED_SCORE_FIELD_NUMBER: _builtins.int
    MAX_SCORE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """@gotags: bson:"_id,omitempty" """
    job_id: _builtins.str
    """@gotags: bson:"job_id" """
    identity_id: _builtins.str
    """@gotags: bson:"identity_id" """
    scoring_status: Global___ScoringStatus.ValueType
    """@gotags: bson:"scoring_status" """
    weighted_score: _builtins.float
    """@gotags: bson:"weighted_score" """
    max_score: _builtins.int
    """@gotags: bson:"max_score,omitempty" """
    @_builtins.property
    def preference_scores(self) -> _containers.RepeatedCompositeFieldContainer[Global___PreferenceScore]:
        """@gotags: bson:"preference_scores,omitempty" """

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        job_id: _builtins.str = ...,
        identity_id: _builtins.str = ...,
        preference_scores: _abc.Iterable[Global___PreferenceScore] | None = ...,
        scoring_status: Global___ScoringStatus.ValueType = ...,
        weighted_score: _builtins.float = ...,
        max_score: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "identity_id", b"identity_id", "job_id", b"job_id", "max_score", b"max_score", "preference_scores", b"preference_scores", "scoring_status", b"scoring_status", "weighted_score", b"weighted_score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JobPreferenceScore: _TypeAlias = JobPreferenceScore  # noqa: Y015

@_typing.final
class Job(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    COMPANY_ID_FIELD_NUMBER: _builtins.int
    COMPANY_INFO_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    LOCATION_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    EXTERNAL_JOB_ID_FIELD_NUMBER: _builtins.int
    SOURCE_URL_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """@gotags: bson:"_id,omitempty" """
    company_id: _builtins.str
    """@gotags: bson:"company_id" """
    title: _builtins.str
    """@gotags: bson:"title" """
    description: _builtins.str
    """@gotags: bson:"description" """
    location: _builtins.str
    """@gotags: bson:"location" """
    platform: _builtins.str
    """@gotags: bson:"platform" """
    external_job_id: _builtins.str
    """@gotags: bson:"external_job_id" """
    source_url: _builtins.str
    """@gotags: bson:"source_url" """
    @_builtins.property
    def company_info(self) -> Global___Company:
        """@gotags: bson:"companyInfo,omitempty" """

    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp:
        """@gotags: bson:"created_at" """

    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp:
        """@gotags: bson:"updated_at" """

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        company_id: _builtins.str = ...,
        company_info: Global___Company | None = ...,
        title: _builtins.str = ...,
        description: _builtins.str = ...,
        location: _builtins.str = ...,
        platform: _builtins.str = ...,
        external_job_id: _builtins.str = ...,
        source_url: _builtins.str = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["company_info", b"company_info", "created_at", b"created_at", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["company_id", b"company_id", "company_info", b"company_info", "created_at", b"created_at", "description", b"description", "external_job_id", b"external_job_id", "id", b"id", "location", b"location", "platform", b"platform", "source_url", b"source_url", "title", b"title", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Job: _TypeAlias = Job  # noqa: Y015

@_typing.final
class CrawlTriggerRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    identity_id: _builtins.str
    def __init__(
        self,
        *,
        identity_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identity_id", b"identity_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CrawlTriggerRequest: _TypeAlias = CrawlTriggerRequest  # noqa: Y015

@_typing.final
class CrawlTriggerQueuePayload(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    REQUESTED_AT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    identity_id: _builtins.str
    @_builtins.property
    def requested_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        identity_id: _builtins.str = ...,
        requested_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["requested_at", b"requested_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identity_id", b"identity_id", "requested_at", b"requested_at", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CrawlTriggerQueuePayload: _TypeAlias = CrawlTriggerQueuePayload  # noqa: Y015

@_typing.final
class WorkflowDispatchMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    COMPANY_ID_FIELD_NUMBER: _builtins.int
    ATS_PROVIDER_FIELD_NUMBER: _builtins.int
    ATS_SLUG_FIELD_NUMBER: _builtins.int
    TRIGGER_KIND_FIELD_NUMBER: _builtins.int
    ATTEMPT_FIELD_NUMBER: _builtins.int
    DISPATCHED_AT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    workflow_run_id: _builtins.str
    workflow_id: _builtins.str
    identity_id: _builtins.str
    company_id: _builtins.str
    ats_provider: _builtins.str
    ats_slug: _builtins.str
    trigger_kind: _builtins.str
    attempt: _builtins.int
    @_builtins.property
    def dispatched_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        workflow_run_id: _builtins.str = ...,
        workflow_id: _builtins.str = ...,
        identity_id: _builtins.str = ...,
        company_id: _builtins.str = ...,
        ats_provider: _builtins.str = ...,
        ats_slug: _builtins.str = ...,
        trigger_kind: _builtins.str = ...,
        attempt: _builtins.int = ...,
        dispatched_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dispatched_at", b"dispatched_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ats_provider", b"ats_provider", "ats_slug", b"ats_slug", "attempt", b"attempt", "company_id", b"company_id", "dispatched_at", b"dispatched_at", "identity_id", b"identity_id", "run_id", b"run_id", "trigger_kind", b"trigger_kind", "workflow_id", b"workflow_id", "workflow_run_id", b"workflow_run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WorkflowDispatchMessage: _TypeAlias = WorkflowDispatchMessage  # noqa: Y015

@_typing.final
class CompanyDiscoveryEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    COMPANY_ID_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    EMITTED_AT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    workflow_run_id: _builtins.str
    workflow_id: _builtins.str
    identity_id: _builtins.str
    company_id: _builtins.str
    reason: _builtins.str
    @_builtins.property
    def emitted_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        workflow_run_id: _builtins.str = ...,
        workflow_id: _builtins.str = ...,
        identity_id: _builtins.str = ...,
        company_id: _builtins.str = ...,
        reason: _builtins.str = ...,
        emitted_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["emitted_at", b"emitted_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["company_id", b"company_id", "emitted_at", b"emitted_at", "identity_id", b"identity_id", "reason", b"reason", "run_id", b"run_id", "workflow_id", b"workflow_id", "workflow_run_id", b"workflow_run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompanyDiscoveryEvent: _TypeAlias = CompanyDiscoveryEvent  # noqa: Y015

@_typing.final
class AtsJobTriggerEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    COMPANY_ID_FIELD_NUMBER: _builtins.int
    ATS_PROVIDER_FIELD_NUMBER: _builtins.int
    ATS_SLUG_FIELD_NUMBER: _builtins.int
    EMITTED_AT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    workflow_run_id: _builtins.str
    workflow_id: _builtins.str
    identity_id: _builtins.str
    company_id: _builtins.str
    ats_provider: _builtins.str
    ats_slug: _builtins.str
    @_builtins.property
    def emitted_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        workflow_run_id: _builtins.str = ...,
        workflow_id: _builtins.str = ...,
        identity_id: _builtins.str = ...,
        company_id: _builtins.str = ...,
        ats_provider: _builtins.str = ...,
        ats_slug: _builtins.str = ...,
        emitted_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["emitted_at", b"emitted_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ats_provider", b"ats_provider", "ats_slug", b"ats_slug", "company_id", b"company_id", "emitted_at", b"emitted_at", "identity_id", b"identity_id", "run_id", b"run_id", "workflow_id", b"workflow_id", "workflow_run_id", b"workflow_run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AtsJobTriggerEvent: _TypeAlias = AtsJobTriggerEvent  # noqa: Y015

@_typing.final
class JobRetireEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    JOB_ID_FIELD_NUMBER: _builtins.int
    EMITTED_AT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    workflow_run_id: _builtins.str
    workflow_id: _builtins.str
    identity_id: _builtins.str
    job_id: _builtins.str
    @_builtins.property
    def emitted_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        workflow_run_id: _builtins.str = ...,
        workflow_id: _builtins.str = ...,
        identity_id: _builtins.str = ...,
        job_id: _builtins.str = ...,
        emitted_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["emitted_at", b"emitted_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["emitted_at", b"emitted_at", "identity_id", b"identity_id", "job_id", b"job_id", "run_id", b"run_id", "workflow_id", b"workflow_id", "workflow_run_id", b"workflow_run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JobRetireEvent: _TypeAlias = JobRetireEvent  # noqa: Y015

@_typing.final
class CrawlProgress(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    WORKFLOW_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    ESTIMATED_TOTAL_FIELD_NUMBER: _builtins.int
    COMPLETED_FIELD_NUMBER: _builtins.int
    PERCENT_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    FINISHED_AT_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    identity_id: _builtins.str
    status: _builtins.str
    workflow: _builtins.str
    message: _builtins.str
    estimated_total: _builtins.int
    completed: _builtins.int
    percent: _builtins.int
    reason: _builtins.str
    workflow_run_id: _builtins.str
    workflow_id: _builtins.str
    @_builtins.property
    def started_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def finished_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        identity_id: _builtins.str = ...,
        status: _builtins.str = ...,
        workflow: _builtins.str = ...,
        message: _builtins.str = ...,
        estimated_total: _builtins.int = ...,
        completed: _builtins.int = ...,
        percent: _builtins.int = ...,
        started_at: _timestamp_pb2.Timestamp | None = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
        finished_at: _timestamp_pb2.Timestamp | None = ...,
        reason: _builtins.str = ...,
        workflow_run_id: _builtins.str = ...,
        workflow_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["finished_at", b"finished_at", "started_at", b"started_at", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completed", b"completed", "estimated_total", b"estimated_total", "finished_at", b"finished_at", "identity_id", b"identity_id", "message", b"message", "percent", b"percent", "reason", b"reason", "run_id", b"run_id", "started_at", b"started_at", "status", b"status", "updated_at", b"updated_at", "workflow", b"workflow", "workflow_id", b"workflow_id", "workflow_run_id", b"workflow_run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CrawlProgress: _TypeAlias = CrawlProgress  # noqa: Y015

@_typing.final
class ScoringProgress(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    IDENTITY_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    ESTIMATED_TOTAL_FIELD_NUMBER: _builtins.int
    COMPLETED_FIELD_NUMBER: _builtins.int
    PERCENT_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    FINISHED_AT_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    identity_id: _builtins.str
    status: _builtins.str
    message: _builtins.str
    estimated_total: _builtins.int
    completed: _builtins.int
    percent: _builtins.int
    reason: _builtins.str
    @_builtins.property
    def started_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def finished_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        identity_id: _builtins.str = ...,
        status: _builtins.str = ...,
        message: _builtins.str = ...,
        estimated_total: _builtins.int = ...,
        completed: _builtins.int = ...,
        percent: _builtins.int = ...,
        started_at: _timestamp_pb2.Timestamp | None = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
        finished_at: _timestamp_pb2.Timestamp | None = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["finished_at", b"finished_at", "started_at", b"started_at", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completed", b"completed", "estimated_total", b"estimated_total", "finished_at", b"finished_at", "identity_id", b"identity_id", "message", b"message", "percent", b"percent", "reason", b"reason", "run_id", b"run_id", "started_at", b"started_at", "status", b"status", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScoringProgress: _TypeAlias = ScoringProgress  # noqa: Y015

@_typing.final
class JobUpdateEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: _builtins.int
    EMITTED_AT_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    workflow_id: _builtins.str
    workflow_run_id: _builtins.str
    @_builtins.property
    def emitted_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        workflow_id: _builtins.str = ...,
        workflow_run_id: _builtins.str = ...,
        emitted_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["emitted_at", b"emitted_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["emitted_at", b"emitted_at", "job_id", b"job_id", "workflow_id", b"workflow_id", "workflow_run_id", b"workflow_run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JobUpdateEvent: _TypeAlias = JobUpdateEvent  # noqa: Y015
