"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ScoringStatus:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ScoringStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ScoringStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SCORING_STATUS_UNSPECIFIED: _ScoringStatus.ValueType  # 0
    SCORING_STATUS_UNSCORED: _ScoringStatus.ValueType  # 1
    SCORING_STATUS_QUEUED: _ScoringStatus.ValueType  # 2
    SCORING_STATUS_SCORED: _ScoringStatus.ValueType  # 3
    SCORING_STATUS_FAILED: _ScoringStatus.ValueType  # 4
    SCORING_STATUS_SKIPPED: _ScoringStatus.ValueType  # 5
class ScoringStatus(_ScoringStatus, metaclass=_ScoringStatusEnumTypeWrapper):
    pass

SCORING_STATUS_UNSPECIFIED: ScoringStatus.ValueType  # 0
SCORING_STATUS_UNSCORED: ScoringStatus.ValueType  # 1
SCORING_STATUS_QUEUED: ScoringStatus.ValueType  # 2
SCORING_STATUS_SCORED: ScoringStatus.ValueType  # 3
SCORING_STATUS_FAILED: ScoringStatus.ValueType  # 4
SCORING_STATUS_SKIPPED: ScoringStatus.ValueType  # 5
global___ScoringStatus = ScoringStatus


class HistoryPart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TEXT_FIELD_NUMBER: builtins.int
    text: typing.Text
    """@gotags: bson:"text" """

    def __init__(self,
        *,
        text: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["text",b"text"]) -> None: ...
global___HistoryPart = HistoryPart

class HistoryEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ROLE_FIELD_NUMBER: builtins.int
    PARTS_FIELD_NUMBER: builtins.int
    role: typing.Text
    """@gotags: bson:"role" """

    @property
    def parts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryPart]:
        """@gotags: bson:"parts" """
        pass
    def __init__(self,
        *,
        role: typing.Text = ...,
        parts: typing.Optional[typing.Iterable[global___HistoryPart]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["parts",b"parts","role",b"role"]) -> None: ...
global___HistoryEntry = HistoryEntry

class CoverLetter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    RECIPIENT_ID_FIELD_NUMBER: builtins.int
    CONVERSATION_ID_FIELD_NUMBER: builtins.int
    COVER_LETTER_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    PROMPT_FIELD_NUMBER: builtins.int
    HISTORY_FIELD_NUMBER: builtins.int
    RECIPIENT_INFO_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id" """

    recipient_id: typing.Text
    """@gotags: bson:"recipient_id" """

    conversation_id: typing.Text
    """@gotags: bson:"conversation_id" """

    cover_letter: typing.Text
    """@gotags: bson:"cover_letter" """

    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"created_at" """
        pass
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"updated_at" """
        pass
    prompt: typing.Text
    """@gotags: bson:"prompt" """

    @property
    def history(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryEntry]:
        """@gotags: bson:"history" """
        pass
    @property
    def recipient_info(self) -> global___Recipient:
        """Recipient info populated by aggregation lookup
        @gotags: bson:"recipientInfo,omitempty"
        """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        recipient_id: typing.Text = ...,
        conversation_id: typing.Text = ...,
        cover_letter: typing.Text = ...,
        created_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        prompt: typing.Text = ...,
        history: typing.Optional[typing.Iterable[global___HistoryEntry]] = ...,
        recipient_info: typing.Optional[global___Recipient] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at",b"created_at","recipient_info",b"recipient_info","updated_at",b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["conversation_id",b"conversation_id","cover_letter",b"cover_letter","created_at",b"created_at","history",b"history","id",b"id","prompt",b"prompt","recipient_id",b"recipient_id","recipient_info",b"recipient_info","updated_at",b"updated_at"]) -> None: ...
global___CoverLetter = CoverLetter

class Field(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    FIELD_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    field: typing.Text
    """@gotags: bson:"field" """

    def __init__(self,
        *,
        id: typing.Text = ...,
        field: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["field",b"field","id",b"id"]) -> None: ...
global___Field = Field

class CompanyDiscoverySource(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOURCE_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    SOURCE_URL_FIELD_NUMBER: builtins.int
    CAREERS_URL_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    source: typing.Text
    """@gotags: bson:"source" """

    role: typing.Text
    """@gotags: bson:"role" """

    source_url: typing.Text
    """@gotags: bson:"source_url,omitempty" """

    careers_url: typing.Text
    """@gotags: bson:"careers_url,omitempty" """

    domain: typing.Text
    """@gotags: bson:"domain,omitempty" """

    def __init__(self,
        *,
        source: typing.Text = ...,
        role: typing.Text = ...,
        source_url: typing.Text = ...,
        careers_url: typing.Text = ...,
        domain: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["careers_url",b"careers_url","domain",b"domain","role",b"role","source",b"source","source_url",b"source_url"]) -> None: ...
global___CompanyDiscoverySource = CompanyDiscoverySource

class DiscoveredCompany(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    SOURCE_URL_FIELD_NUMBER: builtins.int
    CAREERS_URL_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    name: typing.Text
    """@gotags: bson:"name" """

    source: typing.Text
    """@gotags: bson:"source" """

    role: typing.Text
    """@gotags: bson:"role" """

    source_url: typing.Text
    """@gotags: bson:"source_url,omitempty" """

    careers_url: typing.Text
    """@gotags: bson:"careers_url,omitempty" """

    domain: typing.Text
    """@gotags: bson:"domain,omitempty" """

    description: typing.Text
    """@gotags: bson:"description,omitempty" """

    def __init__(self,
        *,
        name: typing.Text = ...,
        source: typing.Text = ...,
        role: typing.Text = ...,
        source_url: typing.Text = ...,
        careers_url: typing.Text = ...,
        domain: typing.Text = ...,
        description: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["careers_url",b"careers_url","description",b"description","domain",b"domain","name",b"name","role",b"role","source",b"source","source_url",b"source_url"]) -> None: ...
global___DiscoveredCompany = DiscoveredCompany

class CompanySlugSearchAttempt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ATTEMPTED_AT_FIELD_NUMBER: builtins.int
    ATTEMPTS_FIELD_NUMBER: builtins.int
    OUTCOME_FIELD_NUMBER: builtins.int
    @property
    def attempted_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"attempted_at,omitempty" """
        pass
    attempts: builtins.int
    """@gotags: bson:"attempts,omitempty" """

    outcome: typing.Text
    """@gotags: bson:"outcome,omitempty" """

    def __init__(self,
        *,
        attempted_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        attempts: builtins.int = ...,
        outcome: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["attempted_at",b"attempted_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["attempted_at",b"attempted_at","attempts",b"attempts","outcome",b"outcome"]) -> None: ...
global___CompanySlugSearchAttempt = CompanySlugSearchAttempt

class Workflow2TerminalFailure(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FAILURE_TYPE_FIELD_NUMBER: builtins.int
    FAILED_AT_FIELD_NUMBER: builtins.int
    LAST_URL_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    failure_type: typing.Text
    """@gotags: bson:"failure_type,omitempty" """

    @property
    def failed_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"failed_at,omitempty" """
        pass
    last_url: typing.Text
    """@gotags: bson:"last_url,omitempty" """

    message: typing.Text
    """@gotags: bson:"message,omitempty" """

    def __init__(self,
        *,
        failure_type: typing.Text = ...,
        failed_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        last_url: typing.Text = ...,
        message: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["failed_at",b"failed_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["failed_at",b"failed_at","failure_type",b"failure_type","last_url",b"last_url","message",b"message"]) -> None: ...
global___Workflow2TerminalFailure = Workflow2TerminalFailure

class Company(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class AtsSlugSearchAttemptsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> global___CompanySlugSearchAttempt: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[global___CompanySlugSearchAttempt] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    FIELD_ID_FIELD_NUMBER: builtins.int
    FIELD_INFO_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CANONICAL_NAME_FIELD_NUMBER: builtins.int
    DISCOVERY_SOURCES_FIELD_NUMBER: builtins.int
    ATS_PROVIDER_FIELD_NUMBER: builtins.int
    ATS_SLUG_FIELD_NUMBER: builtins.int
    ATS_SLUG_SEARCH_ATTEMPTS_FIELD_NUMBER: builtins.int
    WORKFLOW2_TERMINAL_FAILURE_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    name: typing.Text
    """@gotags: bson:"name" """

    field_id: typing.Text
    """@gotags: bson:"field_id" """

    @property
    def field_info(self) -> global___Field:
        """@gotags: bson:"fieldInfo,omitempty" """
        pass
    description: typing.Text
    """@gotags: bson:"description,omitempty" """

    canonical_name: typing.Text
    """@gotags: bson:"canonical_name,omitempty" """

    @property
    def discovery_sources(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CompanyDiscoverySource]:
        """@gotags: bson:"discovery_sources,omitempty" """
        pass
    ats_provider: typing.Text
    """@gotags: bson:"ats_provider,omitempty" """

    ats_slug: typing.Text
    """@gotags: bson:"ats_slug,omitempty" """

    @property
    def ats_slug_search_attempts(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___CompanySlugSearchAttempt]:
        """@gotags: bson:"ats_slug_search_attempts,omitempty" """
        pass
    @property
    def workflow2_terminal_failure(self) -> global___Workflow2TerminalFailure:
        """@gotags: bson:"workflow2_terminal_failure,omitempty" """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        name: typing.Text = ...,
        field_id: typing.Text = ...,
        field_info: typing.Optional[global___Field] = ...,
        description: typing.Text = ...,
        canonical_name: typing.Text = ...,
        discovery_sources: typing.Optional[typing.Iterable[global___CompanyDiscoverySource]] = ...,
        ats_provider: typing.Text = ...,
        ats_slug: typing.Text = ...,
        ats_slug_search_attempts: typing.Optional[typing.Mapping[typing.Text, global___CompanySlugSearchAttempt]] = ...,
        workflow2_terminal_failure: typing.Optional[global___Workflow2TerminalFailure] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["field_info",b"field_info","workflow2_terminal_failure",b"workflow2_terminal_failure"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ats_provider",b"ats_provider","ats_slug",b"ats_slug","ats_slug_search_attempts",b"ats_slug_search_attempts","canonical_name",b"canonical_name","description",b"description","discovery_sources",b"discovery_sources","field_id",b"field_id","field_info",b"field_info","id",b"id","name",b"name","workflow2_terminal_failure",b"workflow2_terminal_failure"]) -> None: ...
global___Company = Company

class Recipient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    COMPANY_ID_FIELD_NUMBER: builtins.int
    COMPANY_INFO_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    email: typing.Text
    """@gotags: bson:"email" """

    name: typing.Text
    """@gotags: bson:"name" """

    description: typing.Text
    """@gotags: bson:"description" """

    company_id: typing.Text
    """@gotags: bson:"company_id" """

    @property
    def company_info(self) -> global___Company:
        """@gotags: bson:"companyInfo,omitempty" """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        email: typing.Text = ...,
        name: typing.Text = ...,
        description: typing.Text = ...,
        company_id: typing.Text = ...,
        company_info: typing.Optional[global___Company] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["company_info",b"company_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["company_id",b"company_id","company_info",b"company_info","description",b"description","email",b"email","id",b"id","name",b"name"]) -> None: ...
global___Recipient = Recipient

class Identity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    IDENTITY_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    FIELD_ID_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    HTML_SIGNATURE_FIELD_NUMBER: builtins.int
    FIELD_INFO_FIELD_NUMBER: builtins.int
    PREFERENCES_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    identity: typing.Text
    """@gotags: bson:"identity" """

    name: typing.Text
    """@gotags: bson:"name" """

    description: typing.Text
    """@gotags: bson:"description" """

    field_id: typing.Text
    """@gotags: bson:"field_id" """

    @property
    def roles(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """@gotags: bson:"roles,omitempty" """
        pass
    html_signature: typing.Text
    """@gotags: bson:"html_signature,omitempty" """

    @property
    def field_info(self) -> global___Field:
        """@gotags: bson:"fieldInfo,omitempty" """
        pass
    @property
    def preferences(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IdentityPreference]:
        """@gotags: bson:"preferences,omitempty" """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        identity: typing.Text = ...,
        name: typing.Text = ...,
        description: typing.Text = ...,
        field_id: typing.Text = ...,
        roles: typing.Optional[typing.Iterable[typing.Text]] = ...,
        html_signature: typing.Text = ...,
        field_info: typing.Optional[global___Field] = ...,
        preferences: typing.Optional[typing.Iterable[global___IdentityPreference]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["field_info",b"field_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description",b"description","field_id",b"field_id","field_info",b"field_info","html_signature",b"html_signature","id",b"id","identity",b"identity","name",b"name","preferences",b"preferences","roles",b"roles"]) -> None: ...
global___Identity = Identity

class IdentityPreference(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    GUIDANCE_FIELD_NUMBER: builtins.int
    WEIGHT_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    key: typing.Text
    """@gotags: bson:"key" """

    guidance: typing.Text
    """@gotags: bson:"guidance,omitempty" """

    weight: builtins.float
    """@gotags: bson:"weight" """

    enabled: builtins.bool
    """@gotags: bson:"enabled" """

    def __init__(self,
        *,
        key: typing.Text = ...,
        guidance: typing.Text = ...,
        weight: builtins.float = ...,
        enabled: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["enabled",b"enabled","guidance",b"guidance","key",b"key","weight",b"weight"]) -> None: ...
global___IdentityPreference = IdentityPreference

class JobPreferenceScore(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    JOB_ID_FIELD_NUMBER: builtins.int
    IDENTITY_ID_FIELD_NUMBER: builtins.int
    PREFERENCE_KEY_FIELD_NUMBER: builtins.int
    PREFERENCE_GUIDANCE_FIELD_NUMBER: builtins.int
    PREFERENCE_WEIGHT_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    RATIONALE_FIELD_NUMBER: builtins.int
    SCORED_AT_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    job_id: typing.Text
    """@gotags: bson:"job_id" """

    identity_id: typing.Text
    """@gotags: bson:"identity_id" """

    preference_key: typing.Text
    """@gotags: bson:"preference_key" """

    preference_guidance: typing.Text
    """@gotags: bson:"preference_guidance,omitempty" """

    preference_weight: builtins.float
    """@gotags: bson:"preference_weight,omitempty" """

    score: builtins.int
    """@gotags: bson:"score" """

    rationale: typing.Text
    """@gotags: bson:"rationale,omitempty" """

    @property
    def scored_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"scored_at,omitempty" """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        job_id: typing.Text = ...,
        identity_id: typing.Text = ...,
        preference_key: typing.Text = ...,
        preference_guidance: typing.Text = ...,
        preference_weight: builtins.float = ...,
        score: builtins.int = ...,
        rationale: typing.Text = ...,
        scored_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["scored_at",b"scored_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","identity_id",b"identity_id","job_id",b"job_id","preference_guidance",b"preference_guidance","preference_key",b"preference_key","preference_weight",b"preference_weight","rationale",b"rationale","score",b"score","scored_at",b"scored_at"]) -> None: ...
global___JobPreferenceScore = JobPreferenceScore

class Job(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    COMPANY_ID_FIELD_NUMBER: builtins.int
    COMPANY_INFO_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    PLATFORM_FIELD_NUMBER: builtins.int
    EXTERNAL_JOB_ID_FIELD_NUMBER: builtins.int
    SOURCE_URL_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    SCORING_STATUS_FIELD_NUMBER: builtins.int
    WEIGHTED_SCORE_FIELD_NUMBER: builtins.int
    MAX_SCORE_FIELD_NUMBER: builtins.int
    SCORES_FIELD_NUMBER: builtins.int
    id: typing.Text
    """@gotags: bson:"_id,omitempty" """

    company_id: typing.Text
    """@gotags: bson:"company_id" """

    @property
    def company_info(self) -> global___Company:
        """@gotags: bson:"companyInfo,omitempty" """
        pass
    title: typing.Text
    """@gotags: bson:"title" """

    description: typing.Text
    """@gotags: bson:"description" """

    location: typing.Text
    """@gotags: bson:"location" """

    platform: typing.Text
    """@gotags: bson:"platform" """

    external_job_id: typing.Text
    """@gotags: bson:"external_job_id" """

    source_url: typing.Text
    """@gotags: bson:"source_url" """

    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"created_at" """
        pass
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """@gotags: bson:"updated_at" """
        pass
    scoring_status: global___ScoringStatus.ValueType
    """@gotags: bson:"scoring_status" """

    weighted_score: builtins.float
    """@gotags: bson:"weighted_score" """

    max_score: builtins.int
    """@gotags: bson:"max_score,omitempty" """

    @property
    def scores(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___JobPreferenceScore]:
        """@gotags: bson:"scores,omitempty" """
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        company_id: typing.Text = ...,
        company_info: typing.Optional[global___Company] = ...,
        title: typing.Text = ...,
        description: typing.Text = ...,
        location: typing.Text = ...,
        platform: typing.Text = ...,
        external_job_id: typing.Text = ...,
        source_url: typing.Text = ...,
        created_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        scoring_status: global___ScoringStatus.ValueType = ...,
        weighted_score: builtins.float = ...,
        max_score: builtins.int = ...,
        scores: typing.Optional[typing.Iterable[global___JobPreferenceScore]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["company_info",b"company_info","created_at",b"created_at","updated_at",b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["company_id",b"company_id","company_info",b"company_info","created_at",b"created_at","description",b"description","external_job_id",b"external_job_id","id",b"id","location",b"location","max_score",b"max_score","platform",b"platform","scores",b"scores","scoring_status",b"scoring_status","source_url",b"source_url","title",b"title","updated_at",b"updated_at","weighted_score",b"weighted_score"]) -> None: ...
global___Job = Job

class CrawlTriggerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTITY_ID_FIELD_NUMBER: builtins.int
    identity_id: typing.Text
    def __init__(self,
        *,
        identity_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["identity_id",b"identity_id"]) -> None: ...
global___CrawlTriggerRequest = CrawlTriggerRequest

class CrawlTriggerQueuePayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_ID_FIELD_NUMBER: builtins.int
    IDENTITY_ID_FIELD_NUMBER: builtins.int
    REQUESTED_AT_FIELD_NUMBER: builtins.int
    run_id: typing.Text
    identity_id: typing.Text
    @property
    def requested_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        run_id: typing.Text = ...,
        identity_id: typing.Text = ...,
        requested_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["requested_at",b"requested_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["identity_id",b"identity_id","requested_at",b"requested_at","run_id",b"run_id"]) -> None: ...
global___CrawlTriggerQueuePayload = CrawlTriggerQueuePayload

class WorkflowDispatchMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_ID_FIELD_NUMBER: builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    IDENTITY_ID_FIELD_NUMBER: builtins.int
    COMPANY_ID_FIELD_NUMBER: builtins.int
    ATS_PROVIDER_FIELD_NUMBER: builtins.int
    ATS_SLUG_FIELD_NUMBER: builtins.int
    TRIGGER_KIND_FIELD_NUMBER: builtins.int
    ATTEMPT_FIELD_NUMBER: builtins.int
    DISPATCHED_AT_FIELD_NUMBER: builtins.int
    run_id: typing.Text
    workflow_run_id: typing.Text
    workflow_id: typing.Text
    identity_id: typing.Text
    company_id: typing.Text
    ats_provider: typing.Text
    ats_slug: typing.Text
    trigger_kind: typing.Text
    attempt: builtins.int
    @property
    def dispatched_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        run_id: typing.Text = ...,
        workflow_run_id: typing.Text = ...,
        workflow_id: typing.Text = ...,
        identity_id: typing.Text = ...,
        company_id: typing.Text = ...,
        ats_provider: typing.Text = ...,
        ats_slug: typing.Text = ...,
        trigger_kind: typing.Text = ...,
        attempt: builtins.int = ...,
        dispatched_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dispatched_at",b"dispatched_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ats_provider",b"ats_provider","ats_slug",b"ats_slug","attempt",b"attempt","company_id",b"company_id","dispatched_at",b"dispatched_at","identity_id",b"identity_id","run_id",b"run_id","trigger_kind",b"trigger_kind","workflow_id",b"workflow_id","workflow_run_id",b"workflow_run_id"]) -> None: ...
global___WorkflowDispatchMessage = WorkflowDispatchMessage

class CompanyDiscoveryEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_ID_FIELD_NUMBER: builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    IDENTITY_ID_FIELD_NUMBER: builtins.int
    COMPANY_ID_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    EMITTED_AT_FIELD_NUMBER: builtins.int
    run_id: typing.Text
    workflow_run_id: typing.Text
    workflow_id: typing.Text
    identity_id: typing.Text
    company_id: typing.Text
    reason: typing.Text
    @property
    def emitted_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        run_id: typing.Text = ...,
        workflow_run_id: typing.Text = ...,
        workflow_id: typing.Text = ...,
        identity_id: typing.Text = ...,
        company_id: typing.Text = ...,
        reason: typing.Text = ...,
        emitted_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["emitted_at",b"emitted_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["company_id",b"company_id","emitted_at",b"emitted_at","identity_id",b"identity_id","reason",b"reason","run_id",b"run_id","workflow_id",b"workflow_id","workflow_run_id",b"workflow_run_id"]) -> None: ...
global___CompanyDiscoveryEvent = CompanyDiscoveryEvent

class AtsJobTriggerEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_ID_FIELD_NUMBER: builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    IDENTITY_ID_FIELD_NUMBER: builtins.int
    COMPANY_ID_FIELD_NUMBER: builtins.int
    ATS_PROVIDER_FIELD_NUMBER: builtins.int
    ATS_SLUG_FIELD_NUMBER: builtins.int
    EMITTED_AT_FIELD_NUMBER: builtins.int
    run_id: typing.Text
    workflow_run_id: typing.Text
    workflow_id: typing.Text
    identity_id: typing.Text
    company_id: typing.Text
    ats_provider: typing.Text
    ats_slug: typing.Text
    @property
    def emitted_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        run_id: typing.Text = ...,
        workflow_run_id: typing.Text = ...,
        workflow_id: typing.Text = ...,
        identity_id: typing.Text = ...,
        company_id: typing.Text = ...,
        ats_provider: typing.Text = ...,
        ats_slug: typing.Text = ...,
        emitted_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["emitted_at",b"emitted_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ats_provider",b"ats_provider","ats_slug",b"ats_slug","company_id",b"company_id","emitted_at",b"emitted_at","identity_id",b"identity_id","run_id",b"run_id","workflow_id",b"workflow_id","workflow_run_id",b"workflow_run_id"]) -> None: ...
global___AtsJobTriggerEvent = AtsJobTriggerEvent

class CrawlProgress(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_ID_FIELD_NUMBER: builtins.int
    IDENTITY_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    WORKFLOW_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ESTIMATED_TOTAL_FIELD_NUMBER: builtins.int
    COMPLETED_FIELD_NUMBER: builtins.int
    PERCENT_FIELD_NUMBER: builtins.int
    STARTED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    FINISHED_AT_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    WORKFLOW_RUN_ID_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    run_id: typing.Text
    identity_id: typing.Text
    status: typing.Text
    workflow: typing.Text
    message: typing.Text
    estimated_total: builtins.int
    completed: builtins.int
    percent: builtins.int
    @property
    def started_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finished_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    reason: typing.Text
    workflow_run_id: typing.Text
    workflow_id: typing.Text
    def __init__(self,
        *,
        run_id: typing.Text = ...,
        identity_id: typing.Text = ...,
        status: typing.Text = ...,
        workflow: typing.Text = ...,
        message: typing.Text = ...,
        estimated_total: builtins.int = ...,
        completed: builtins.int = ...,
        percent: builtins.int = ...,
        started_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        finished_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        reason: typing.Text = ...,
        workflow_run_id: typing.Text = ...,
        workflow_id: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["finished_at",b"finished_at","started_at",b"started_at","updated_at",b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["completed",b"completed","estimated_total",b"estimated_total","finished_at",b"finished_at","identity_id",b"identity_id","message",b"message","percent",b"percent","reason",b"reason","run_id",b"run_id","started_at",b"started_at","status",b"status","updated_at",b"updated_at","workflow",b"workflow","workflow_id",b"workflow_id","workflow_run_id",b"workflow_run_id"]) -> None: ...
global___CrawlProgress = CrawlProgress

class ScoringProgress(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_ID_FIELD_NUMBER: builtins.int
    IDENTITY_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ESTIMATED_TOTAL_FIELD_NUMBER: builtins.int
    COMPLETED_FIELD_NUMBER: builtins.int
    PERCENT_FIELD_NUMBER: builtins.int
    STARTED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    FINISHED_AT_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    run_id: typing.Text
    identity_id: typing.Text
    status: typing.Text
    message: typing.Text
    estimated_total: builtins.int
    completed: builtins.int
    percent: builtins.int
    @property
    def started_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finished_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    reason: typing.Text
    def __init__(self,
        *,
        run_id: typing.Text = ...,
        identity_id: typing.Text = ...,
        status: typing.Text = ...,
        message: typing.Text = ...,
        estimated_total: builtins.int = ...,
        completed: builtins.int = ...,
        percent: builtins.int = ...,
        started_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        finished_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        reason: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["finished_at",b"finished_at","started_at",b"started_at","updated_at",b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["completed",b"completed","estimated_total",b"estimated_total","finished_at",b"finished_at","identity_id",b"identity_id","message",b"message","percent",b"percent","reason",b"reason","run_id",b"run_id","started_at",b"started_at","status",b"status","updated_at",b"updated_at"]) -> None: ...
global___ScoringProgress = ScoringProgress
